### ISSUE TITLE
Some tests are repeated two times

### ISSUE THREAD

**Issue by tyyko** [cloudfoundry-incubator/bosh-workspace#114]
While analysing the release test file for #113 , I noticed something weird:

[These tests here](https://github.com/cloudfoundry-incubator/bosh-workspace/blob/master/spec/release_spec.rb#L277-L339) are repeated again [here](https://github.com/cloudfoundry-incubator/bosh-workspace/blob/master/spec/release_spec.rb#L354-L416)

Is there any reason for that?

**Comment by rkoster** [comment]
If I remember correctly the difference is [given a release with deprecated structure within 'releases' folder](https://github.com/cloudfoundry-incubator/bosh-workspace/blob/master/spec/release_spec.rb#L244).
