### ISSUE TITLE
Working with BOSH deployment properties

### ISSUE THREAD

**Issue by allomov** [cloudfoundry-incubator/bosh-workspace#118]
At this moment BOSH has ability to [parse manifests with ERB](https://github.com/cloudfoundry/bosh/blob/master/bosh_cli/lib/cli/deployment_manifest_compiler.rb#L18), this allows to set properties on director side and use them in manifest ([example from tests](https://github.com/cloudfoundry/bosh/blob/672b542911f6056da2ebb1558a76b3bd74f3cf00/bosh_cli/spec/unit/deployment_manifest_compiler_spec.rb#L39), [code from bosh cli that fetches properties from director](https://github.com/cloudfoundry/bosh/blob/1b60860a27d0b39547834f28e1df145c225c4164/bosh_cli/lib/cli/manifest.rb#L37)).

This is really cool feature and I am wondering if bosh-workspace is going to support it.

**Comment by cppforlife** [comment]
that will be a deprecated feature shortly and will be going away soon.

-dk

**Comment by allomov** [comment]
@cppforlife feature with properties on director side sounded interesting. could you tell why do you deprecate it and what do you plan to use instead of it?

**Comment by allomov** [comment]
@cppforlife could you reveal details on deprecation of deployment properties. thank you.

**Comment by allomov** [comment]
@cppforlife any details?
