### ISSUE TITLE
No way to skip drain scripts

### ISSUE THREAD

**Issue by yulianedyalkova** [cloudfoundry-incubator/bosh-workspace#122]
In the boch-cli there is a --skip-drain option when executing bosh deploy/stop/restart etc.

Since the bosh-workspace overwrites those commands, the flags get lost and as far as I know there is no way to actually skip the drain scripts.

**Comment by rkoster** [comment]
Could be fixed with a similar PR as https://github.com/cloudfoundry-incubator/bosh-workspace/pull/121, maybe also include all other options which are currently not exposed.

**Comment by georgi-lozev** [comment]
What is necessary in order to have a public release with the changes introduced with #125 ?

**Comment by rkoster** [comment]
Just someone asking for it 😛, just release [0.9.14](https://rubygems.org/gems/bosh-workspace/versions/0.9.14)

**Comment by georgi-lozev** [comment]
Thank you! : )
