### ISSUE TITLE
Bump semi_semantic to ~>1.2.0

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry-incubator/bosh-workspace#124]
BOSH has updated its dependecy to semi_semantic in version ~>1.2.0 (Gemfile.lock contains 1.2.0 exactly as of now), which makes it incompatible with the ~>1.1.0 restriction in bosh-workspace. Thus, I can't use bosh-workspace with newer versions of the bosh CLI.

If you don't really need to lock down semi_semantic to 1.1.0, an update would be great.

**Comment by rkoster** [comment]
@voelzmo could you test if the above fixes your issue?

**Comment by rkoster** [comment]
if so I will publish a new version

**Comment by voelzmo** [comment]
Wow, that was fast, @rkoster!
Fixes my problem, I tried:
* `gem build bosh-workspace.gemspec`
* `gem install bosh-workspace-0.9.12.gem`
* `bosh -v`

and it worked.

**Comment by afritzler** [comment]
Thanks for resolving. Was running into the same problem over here.

**Comment by tyyko** [comment]
Same for me :) Thanks!

**Comment by rkoster** [comment]
[0.9.13 has been published](https://rubygems.org/gems/bosh-workspace/versions/0.9.13) @voelzmo thanks for testing!
