### ISSUE TITLE
bosh prepare deployment raises error in project_deployment_helper.rb:18

### ISSUE THREAD

**Issue by weberstephanhd** [cloudfoundry-incubator/bosh-workspace#50]
$ bosh prepare deployment
/Users/sw/.rvm/gems/ruby-2.1.4/gems/bosh-workspace-0.8.5/lib/bosh/workspace/helpers/project_deployment_helper.rb:18:in 'project_deployment_file?': undefined method 'has_key?' for "<%\nrequire_relative \"./lib/helper\"":String (NoMethodError)
	from /Users/sw/.rvm/gems/ruby-2.1.4/gems/bosh-workspace-0.8.5/lib/bosh/workspace/helpers/project_deployment_helper.rb:6:in 'project_deployment?'
	from /Users/sw/.rvm/gems/ruby-2.1.4/gems/bosh-workspace-0.8.5/lib/bosh/workspace/helpers/project_deployment_helper.rb:22:in 'require_project_deployment'
	from /Users/sw/.rvm/gems/ruby-2.1.4/gems/bosh-workspace-0.8.5/lib/bosh/cli/commands/prepare.rb:14:in 'prepare'
	from /Users/sw/.rvm/gems/ruby-2.1.4/gems/bosh_cli-1.2922.0/lib/cli/command_handler.rb:57:in 'run'
	from /Users/sw/.rvm/gems/ruby-2.1.4/gems/bosh_cli-1.2922.0/lib/cli/runner.rb:56:in 'run'
	from /Users/sw/.rvm/gems/ruby-2.1.4/gems/bosh_cli-1.2922.0/bin/bosh:16:in '<top (required)>'
	from /Users/sw/.rvm/gems/ruby-2.1.4/bin/bosh:23:in 'load'
	from /Users/sw/.rvm/gems/ruby-2.1.4/bin/bosh:23:in 'main'
	from /Users/sw/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in 'eval'
	from /Users/sw/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in 'main' 

I used a clean ruby 2.1.4 and only installed the following:
gem install bundler --no-rdoc --no-ri
gem install net-ssh --no-rdoc --no-ri
gem install bosh_cli --no-ri --no-rdoc
gem install bosh_cli_plugin_micro --no-ri --no-rdoc 
gem install nats cf-uaac --no-ri --no-rdoc
gem install bosh-workspace --no-ri --no-rdoc

What am I missing?
Best regards, Stephan

**Comment by rkoster** [comment]
@weberstephanhd can you post your deployment file (`bosh deployment`). Since it looks like there is some ERB in your deployment file (`<%\nrequire_relative \"./lib/helper\`)

**Comment by weberstephanhd** [comment]
Thanks for the quick answer. See
see https://gist.github.com/weberstephanhd/1d49e20532738d6141f4

I just found that we use a fork of bosh-workspace which is able to handle that ruby code.
Sorry for the inconvenience.
