### ISSUE TITLE
missing credentials file error, though no credentials are needed 

### ISSUE THREAD

**Issue by weberstephanhd** [cloudfoundry-incubator/bosh-workspace#67]
Our grafana-boshworkspace uses a grafana-boshrelease from a public git repo. No credentials are needed for cloning/fetching and with bosh-workspace 0.8.5 everything works fine.

Using bosh-workspace 0.9.0 on the same bws I get the following error with bosh prepare deployment:

"Authentication is required for: https://github.wdf.sap.corp/cloudfoundry/grafana-boshrelease.git
Credentials file does not exist: /home/vcap/landscape-dev06/bosh-workspaces/grafana-boshworkspace/.credentials.yml". 

best regards, Stephan

**Comment by rkoster** [comment]
Bosh-workspace 0.9.0 changed the git backend from [ruby-git](https://github.com/schacon/ruby-git) to  [rugged](https://github.com/libgit2/rugged). The error you are seeing means [`check_connection`](https://github.com/cloudfoundry-incubator/bosh-workspace/blob/master/lib/bosh/workspace/helpers/git_credentials_helper.rb#L37) returns false. Unfortunately check_connection only retruns true of false which means bosh-workspace can not display a more helpful message.

**Comment by weberstephanhd** [comment]
Wow. What a fast answer. Thank You!
Digging a little deeper brings me to 
Invalid credentials for: https://github.wdf.sap.corp/cloudfoundry/grafana-boshrelease.git
/home/vcap/.rvm/gems/ruby-2.1.2@bosh-1.3001.0.1/gems/rugged-0.23.0b4/lib/rugged/repository.rb:210:in `fetch': The SSL certificate is invalid (Rugged::SslError)
        from /home/vcap/.rvm/gems/ruby-2.1.2@bosh-1.3001.0.1/gems/rugged-0.23.0b4/lib/rugged/repository.rb:210:in `fetch'

Seems like I have to add our internal root certificate to the keystore which rugged uses. Do you know which keystore file rugged uses by default?

Best regards, Stephan

**Comment by rkoster** [comment]
Sorry I don't know which keystore rugged is using, but let me know when you find out because I'm interested as well. But I don't have time to investigate right now (I'm on vacation).

**Comment by weberstephanhd** [comment]
I added the CA.crt to /etc/ssl/certs/ and it's content to /etc/ssl/certs/ca-certificates.crt, called c_rehash then all worked - on ubuntu. Thanks and enjoy your vacation!

**Comment by skibum55** [comment]
Stephan, are you planning on making your grafana bosh release available on bosh.io?

**Comment by buddycao** [comment]
I also encountered this issue. create the .credentials.yml in your bosh-workspace. And add the following content in it.
- url: https://github.com/example/top-secret-boshrelease.git
  username: foo
  password: bar
