### ISSUE TITLE
Could we have a new release

### ISSUE THREAD

**Issue by holgero** [cloudfoundry-incubator/bosh-workspace#73]
Hi @rkoster, 

Could you please create a 0.9.2 release?

Best Regards,
Holger.

**Comment by rkoster** [comment]
Fixed in https://github.com/cloudfoundry-incubator/bosh-workspace/commit/56fda9d8f42e07ec3a549d39a68fca3873fc2bf8

**Comment by holgero** [comment]
Many, many thanks! It amazes me again and again how fast you react. A special 'thank you' for that!

**Comment by rkoster** [comment]
I'm glad I could help :smile:
