### ISSUE TITLE
bosh prepare deployment fails with recent stemcells

### ISSUE THREAD

**Issue by sklevenz** [cloudfoundry-incubator/bosh-workspace#84]
recent stemcells for bosh-lite can no longer be accessed using

'bosh public stemcells'

used internally by bosh prepare deployment.

Since 'bosh public stemcells' is going to be deprecated, we propose to construct the stemcell URL using

https://bosh.io/d/stemcells/#{stemcell.name}?v=#{stemcell.version}

and just use 'bosh upload stemcell <URL>', i.e. let bosh do the download remotely. Patch to follow.

**Comment by rkoster** [comment]
Fixed in the above PR
