### ISSUE TITLE
Edge case on validation: stemcell version '0000'

### ISSUE THREAD

**Issue by pronoiac** [cloudfoundry-incubator/bosh-workspace#90]
I'm using an alpha stemcell with version 0000, and the validation stops that cold. Plz help!

**Comment by allomov** [comment]
Could you provide more details on this case?

**Comment by rkoster** [comment]
Have been pairing with @pronoiac, we where deploying on Azure and found that their stemcell for some reason has the '0000' version number. The validation for stemcells [here](https://github.com/cloudfoundry-incubator/bosh-workspace/blob/master/lib/bosh/workspace/schemas/stemcells.rb#L15-L25) would fail to validate.
