### ISSUE TITLE
Referencing a local BOSH (dev) release in deployment file (manifest)

### ISSUE THREAD

**Issue by djvdorp** [cloudfoundry-incubator/bosh-workspace#91]
I am trying to reference a local BOSH (dev) release in my deployment file (manifest), however, I either don't completely understand how to do this, or I might just be doing it wrong.

Relevant information and versions:
```
bosh 1.2950.0
bosh-workspace 0.9.0
```

Let's say I started out with something like this:

deployment file (manifest):
```yaml
---
name: xxx
director_uuid: xxx

releases:
  - name: cf
    version: 212
    git: https://github.com/cloudfoundry/cf-release.git
```

However, I needed to customize some things within the cf-release, and after doing so, I created a development release on my BOSH box.

bosh releases:
```shell
+------+------------+-------------+
| Name | Versions   | Commit Hash |
+------+------------+-------------+
| cf   | 212        | ae2ec7a5+   |
|      | 212+dev.1* | b30e0fd5+   |
+------+------------+-------------+
(*) Currently deployed
(+) Uncommitted changes
```

But, now I want to be able to run ```bosh prepare deployment``` while referencing my (own, local) BOSH (dev) release in my deployment file (manifest), which (I think) should look something like this:

deployment file (manifest):
```yaml
---
name: xxx
director_uuid: xxx

releases:
  - name: cf
    version: 212+dev.1
    #git: https://github.com/cloudfoundry/cf-release.git
    #there should probably be some other reference here, to tell bosh-workspace where it can find the 212+dev.1 release?
```

Can you help me out here on how to get this working?
I don't have a (public or private) git repository to point to, so that might be an issue.
However, the BOSH director does hold this local BOSH (dev) release somewhere, and it is also on my local disk (```cf/dev_releases/cf/212+dev.1.yml```).

**Comment by allomov** [comment]
I also stucked with such problem once. At this moment I don't have access to that environment to test it, but here are my guesses: you can try to create symlink of folder with your custom release in `.releases` folder

If this won't help there is another solution: you can tell your deployment manifest to use 212 release, but set release through stub file like this
```
releases:
  - name: cf
    version: 212+dev.1
```
The feature with stubs was added in version `0.9.4` so you'll need to update your bosh-workspace.

**Comment by djvdorp** [comment]
Thanks for your reply @allomov ! Much appreciated. I tried your following suggestions, and here are my findings on them (after upgrading bosh-workspace to 0.9.4):

> you can try to create symlink of folder with your custom release in ```.releases``` folder
> @allomov 

I did not (yet) manage to get this working, maybe because I am symlinking the wrong directory in ```.releases``` folder? These are the folders I have available, which one should I symlink, you think?
```shell
total 348
drwxrwxr-x 21 ubuntu ubuntu   4096 Dec 16 10:19 .
drwxrwxr-x  4 ubuntu ubuntu   4096 Dec 16 16:04 ..
drwxrwxr-x 23 ubuntu ubuntu   4096 Nov 30 12:30 blobs
drwxrwxr-x  2 ubuntu ubuntu   4096 Nov 30 12:30 .blobs
drwxr-xr-x  3 ubuntu ubuntu   4096 Dec 16 10:19 bosh-lite
drwxr-xr-x  2 ubuntu ubuntu   4096 Dec 16 16:10 config
-rw-r--r--  1 ubuntu ubuntu   3413 Dec 16 10:19 CONTRIBUTING.md
drwxrwxr-x  5 ubuntu ubuntu   4096 Nov 30 12:50 .dev_builds
drwxrwxr-x  3 ubuntu ubuntu   4096 Nov 30 12:50 dev_releases
drwxr-xr-x  2 ubuntu ubuntu   4096 Oct 28 22:35 docs
drwxr-xr-x  2 ubuntu ubuntu   4096 Oct 28 22:35 example_manifests
drwxr-xr-x  5 ubuntu ubuntu   4096 Oct 28 22:35 .final_builds
-rw-r--r--  1 ubuntu ubuntu    176 Oct 28 22:35 Gemfile
-rw-r--r--  1 ubuntu ubuntu   4171 Dec 16 10:19 Gemfile.lock
drwxrwxr-x  8 ubuntu ubuntu   4096 Dec 16 15:46 .git
-rw-r--r--  1 ubuntu ubuntu     52 Oct 28 22:35 .gitattributes
drwxr-xr-x  2 ubuntu ubuntu   4096 Dec 16 10:19 git_hooks
-rw-r--r--  1 ubuntu ubuntu    294 Dec 16 10:19 .gitignore
-rw-r--r--  1 ubuntu ubuntu   4059 Dec 16 10:19 .gitmodules
drwxr-xr-x 19 ubuntu ubuntu   4096 Dec 16 10:19 jobs
-rw-r--r--  1 ubuntu ubuntu 214117 Oct 28 22:35 LICENSE
-rw-r--r--  1 ubuntu ubuntu    467 Oct 28 22:35 NOTICE
drwxr-xr-x 38 ubuntu ubuntu   4096 Dec 16 10:19 packages
drwxr-xr-x  2 ubuntu ubuntu   4096 Oct 28 22:35 pipeline-image
-rw-r--r--  1 ubuntu ubuntu   8267 Dec 16 10:19 README.md
drwxr-xr-x  2 ubuntu ubuntu   4096 Dec 16 10:19 releases
-rw-r--r--  1 ubuntu ubuntu      8 Oct 28 22:35 .rspec
-rw-r--r--  1 ubuntu ubuntu      6 Dec 16 10:19 .ruby-version
drwxr-xr-x  2 ubuntu ubuntu   4096 Dec 16 10:19 scripts
drwxr-xr-x  4 ubuntu ubuntu   4096 Dec 16 10:19 spec
drwxr-xr-x 21 ubuntu ubuntu   4096 Dec 16 10:19 src
drwxr-xr-x  2 ubuntu ubuntu   4096 Dec 16 10:19 templates
```

> you can tell your deployment manifest to use 212 release, but set release through stub file like this
> @allomov 

I created a stub file in ```stubs/stub.yml``` like this:
```yaml
---
releases:
  - name: cf
    version: 212+dev.1
```

However, that gave me this error: ```Key: 'releases' not allowed in stub file```

**Comment by rkoster** [comment]
@djvdorp what I usually do when I use a dev release is upload the release manually (so not using `bosh prepare deployment` but by using `bosh upload release`) and then in `deployments/{deployment_name}.yml` I would put:
```yaml
releases:
  - name: {release_name}
    version: latest
```

This is not idea but I found my self usually just using `./templates/make_manifest warden` (as generated by `bosh-gen`) when developing a bosh-release. And use bosh-workspace when deploying to a real environment.
